# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Victor
#
# This file is part of subcanopy-gateway. See LICENSE and
# COMMERCIAL_LICENSE.md at the repository root.

"""create scan_records table

Revision ID: 2cab5e617849
Revises:
Create Date: 2026-10-02 08:39:36.180991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cab5e617849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk', sa.Float(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_records_created_at'), 'scan_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_records_severity'), 'scan_records', ['severity'], unique=False)
    op.create_index(op.f('ix_scan_records_source'), 'scan_records', ['source'], unique=False)
    op.create_index(op.f('ix_scan_records_text_hash'), 'scan_records', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_records_text_hash'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_source'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_severity'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_created_at'), table_name='scan_records')
    op.drop_table('scan_records')
    # ### end Alembic commands ###
