# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Victor
#
# This file is part of subcanopy-gateway. See LICENSE and
# COMMERCIAL_LICENSE.md at the repository root.

"""create attack_patterns table

Revision ID: 9cfaa592e49d
Revises: 8638b6b551fc
Create Date: 2026-10-02 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '9cfaa592e49d'
down_revision: Union[str, Sequence[str], None] = '8638b6b551fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_patterns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_corpus', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_patterns_category'), 'attack_patterns', ['category'], unique=False)
    op.create_index(op.f('ix_attack_patterns_name'), 'attack_patterns', ['name'], unique=True)
    op.create_index(op.f('ix_attack_patterns_source_corpus'), 'attack_patterns', ['source_corpus'], unique=False)
    op.create_index(
        'ix_attack_patterns_embedding_hnsw',
        'attack_patterns',
        ['embedding'],
        unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attack_patterns_embedding_hnsw', table_name='attack_patterns')
    op.drop_index(op.f('ix_attack_patterns_source_corpus'), table_name='attack_patterns')
    op.drop_index(op.f('ix_attack_patterns_name'), table_name='attack_patterns')
    op.drop_index(op.f('ix_attack_patterns_category'), table_name='attack_patterns')
    op.drop_table('attack_patterns')
    # ### end Alembic commands ###
